config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :images
  

  get 'probar', to: 'default#saludo'


  get 'holas/:hola', to: 'home#hola'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :picture, PictureUploader

	validates :description, presence: true

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_devise_params, if: :devise_controller?

  def configure_devise_params
  	devise_parameter_sanitizer.permit(:sign_up) do |user|
  		user.permit(:name, :email, :password, :password_confirmation)
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
      @images = Image.paginate(page: params[:page], per_page: 1)
                     .order(id: :desc)
                     .where user_id: current_user.id
  	end
  end

  def hola
  	@hola = params[:hola]
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_image, only: [:show, :edit, :update, :destroy]

	def new
		@image = Image.new
	end

	def index
		@images = Image.where user_id: current_user.id
	end

	def create
		@image  = current_user.images.new image_params
		if @image.save
			return redirect_to @image
		end
		render :new
	end

	def show
	end

	def edit
	end

	def update
		@image.update image_params
		redirect_to @image
	end

	def destroy
		@image.destroy
		redirect_to images_path
	end

	private

	def image_params
		params.require(:image).permit :description, :picture
	end

	def set_image
		@image = Image.find params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/hola.html.erb
<p><%= @hola %></p>

app/views/home/index.html.erb
<%- if user_signed_in? %>	<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNav">
        <h4><%= current_user.name %></h4>
        <ul class="navbar-nav">
          <li class="nav-item">
            <p class="nav-link">
              Informacion
            </p>
          </li>
          <li class="nav-item">
            <p class="nav-link">
            	<%= @images.count %> publicaciones
            </p>
          </li>
        </ul>
      </div>
    </nav>
	<br>
<div class="container">
	<div class="row" id='images'> 
		<%= render @images %>
	</div>
</div>

<%= will_paginate @images %>
<% else %>
	<h1>Bienvenido a SalvaGram</h1>
<% end %>

app/views/home/index.js.erb
$('#images').append('<%= j render @images %>')

<% if @images.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @images %>')
<% else %>
  $('.pagination').remove();
<% end %>

app/views/images/_form.html.erb
<div class="form-group">
	<%= form_for @image, builder: CustomFormBuilder do |f| %>
		<%= f.form_error %>

		<%= f.label  :description %>
		<br> 
		<%= f.text_field :description, class: 'form-control' %>
		<%= f.field_error :description %>
		<br>
		<%= f.label  :picture %>
		<br>
		<%= f.file_field :picture %>
		<br>
		<br>
		<%= f.submit 'Enviar', class: 'btn btn-primary'%>
	<% end %>
</div>

app/views/images/_image.html.erb
<div class="col-4">
  <figure class="figure">
  <a href="<%=image_path(image)%>">
  	 <%= image_tag image.picture.thumb.url, class: 'figure-img img-fluid rounded'%>

  </a>
    <figcaption class="figure-caption"><%= image.description %>
      <%= link_to t('.edit_link'), edit_image_path(image) %>
      <%= link_to t('.remove_link'), image, method: :delete, data: { confirm: 'Esta seguro?'} %>
    </figcaption>
  </figure>
</div>

app/views/images/edit.html.erb
<div class="container">
	<h3>Editar</h3>
	<%= render 'form' %>
</div>

app/views/images/index.html.erb
<br>
<div class="container">
	<div class="row"> 
		<%= render @images %>

	</div>
</div>

app/views/images/new.html.erb
<div class="container">
	<p>Nueva imagen</p>
	<%= render 'form' %>
</div>

app/views/images/show.html.erb
<div class="row">

	<div class="col-md-12 text-center">
		<%= image_tag @image.picture.thumb.url, class: 'img-fluid rounded img-thumbnail'%>
	</div>
	<br>
	<div class="col-md-12 text-center">
		<%= @image.description %>
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Red</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark"">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <%- if  user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Nueva Imagen', new_image_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to 'Cambiar Contra', edit_user_registration_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: 'nav-link'%>
            </li>
           
            
          <% else %>
            <li class="nav-item">
              <%= link_to 'Iniciar', new_user_session_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to 'Registrarme', new_user_registration_path, class: 'nav-link'%>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="card col-12">
      <%= yield %>
    </div>

   
  </body>
</html>